
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/Users/grzeg/Desktop/font/Font.xml
* name: Font
* family: Verdana
* size: 14
* style: Pogrubiony
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x0090
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/
#include "EID_Bitmap.h"


#include <stdint.h>



#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x20[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x20 = { image_data_Font_0x20,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x21[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██████
    // ██∙∙██
    // ██∙∙██
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xfc, 
    0xcc, 
    0xcc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x21 = { image_data_Font_0x21,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x22[17] = {
    // ████████
    // ████████
    // ████████
    // █∙∙██∙∙█
    // █∙∙██∙∙█
    // █∙∙██∙∙█
    // █∙∙██∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0x99, 
    0x99, 
    0x99, 
    0x99, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x22 = { image_data_Font_0x22,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x23[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █████∙███∙██
    // █████∙███∙██
    // ██∙∙∙∙∙∙∙∙∙█
    // ██∙∙∙∙∙∙∙∙∙█
    // ████∙███∙███
    // ███∙███∙████
    // █∙∙∙∙∙∙∙∙∙██
    // █∙∙∙∙∙∙∙∙∙██
    // ██∙███∙█████
    // ██∙███∙█████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xfb, 0xb0, 
    0xfb, 0xb0, 
    0xc0, 0x10, 
    0xc0, 0x10, 
    0xf7, 0x70, 
    0xee, 0xf0, 
    0x80, 0x30, 
    0x80, 0x30, 
    0xdd, 0xf0, 
    0xdd, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x23 = { image_data_Font_0x23,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x24[34] = {
    // ██████████
    // ██████████
    // █████∙████
    // █████∙████
    // ███∙∙∙∙∙██
    // ██∙∙█∙██∙█
    // █∙∙██∙████
    // █∙∙∙█∙████
    // ██∙∙∙∙████
    // ████∙∙∙∙██
    // ████∙█∙∙∙█
    // ████∙██∙∙█
    // █∙██∙█∙∙██
    // ██∙∙∙∙∙███
    // ████∙█████
    // ████∙█████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xfb, 0xc0, 
    0xfb, 0xc0, 
    0xe0, 0xc0, 
    0xcb, 0x40, 
    0x9b, 0xc0, 
    0x8b, 0xc0, 
    0xc3, 0xc0, 
    0xf0, 0xc0, 
    0xf4, 0x40, 
    0xf6, 0x40, 
    0xb4, 0xc0, 
    0xc1, 0xc0, 
    0xf7, 0xc0, 
    0xf7, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x24 = { image_data_Font_0x24,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x25[51] = {
    // ██████████████████
    // ██████████████████
    // ██████████████████
    // ██████████████████
    // ██∙∙∙∙██████∙█████
    // █∙∙██∙∙████∙██████
    // █∙∙██∙∙███∙███████
    // █∙∙██∙∙███∙█∙∙∙∙██
    // █∙∙██∙∙██∙█∙∙██∙∙█
    // █∙∙██∙∙█∙██∙∙██∙∙█
    // ██∙∙∙∙█∙███∙∙██∙∙█
    // ███████∙███∙∙██∙∙█
    // ██████∙████∙∙██∙∙█
    // █████∙██████∙∙∙∙██
    // ██████████████████
    // ██████████████████
    // ██████████████████
    0xff, 0xff, 0xc0, 
    0xff, 0xff, 0xc0, 
    0xff, 0xff, 0xc0, 
    0xff, 0xff, 0xc0, 
    0xc3, 0xf7, 0xc0, 
    0x99, 0xef, 0xc0, 
    0x99, 0xdf, 0xc0, 
    0x99, 0xd0, 0xc0, 
    0x99, 0xa6, 0x40, 
    0x99, 0x66, 0x40, 
    0xc2, 0xe6, 0x40, 
    0xfe, 0xe6, 0x40, 
    0xfd, 0xe6, 0x40, 
    0xfb, 0xf0, 0xc0, 
    0xff, 0xff, 0xc0, 
    0xff, 0xff, 0xc0, 
    0xff, 0xff, 0xc0
};
static const tImage Font_0x25 = { image_data_Font_0x25,
    18, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x26[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ███∙∙∙∙█████
    // ██∙∙██∙∙████
    // ██∙∙██∙∙████
    // ██∙∙█∙∙█████
    // ███∙∙∙███∙∙█
    // ██∙∙█∙∙██∙∙█
    // █∙∙███∙∙█∙∙█
    // █∙∙████∙∙∙██
    // ██∙∙███∙∙∙██
    // ███∙∙∙∙∙█∙∙█
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xe1, 0xf0, 
    0xcc, 0xf0, 
    0xcc, 0xf0, 
    0xc9, 0xf0, 
    0xe3, 0x90, 
    0xc9, 0x90, 
    0x9c, 0x90, 
    0x9e, 0x30, 
    0xce, 0x30, 
    0xe0, 0x90, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x26 = { image_data_Font_0x26,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x27[17] = {
    // █████
    // █████
    // █████
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0x98, 
    0x98, 
    0x98, 
    0x98, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x27 = { image_data_Font_0x27,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x28[17] = {
    // ████████
    // ████████
    // ████████
    // ████∙∙██
    // ███∙∙███
    // ██∙∙████
    // ██∙∙████
    // █∙∙█████
    // █∙∙█████
    // █∙∙█████
    // █∙∙█████
    // █∙∙█████
    // █∙∙█████
    // ██∙∙████
    // ██∙∙████
    // ███∙∙███
    // ████∙∙██
    0xff, 
    0xff, 
    0xff, 
    0xf3, 
    0xe7, 
    0xcf, 
    0xcf, 
    0x9f, 
    0x9f, 
    0x9f, 
    0x9f, 
    0x9f, 
    0x9f, 
    0xcf, 
    0xcf, 
    0xe7, 
    0xf3
};
static const tImage Font_0x28 = { image_data_Font_0x28,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x29[17] = {
    // ████████
    // ████████
    // ████████
    // ██∙∙████
    // ███∙∙███
    // ████∙∙██
    // ████∙∙██
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // ████∙∙██
    // ████∙∙██
    // ███∙∙███
    // ██∙∙████
    0xff, 
    0xff, 
    0xff, 
    0xcf, 
    0xe7, 
    0xf3, 
    0xf3, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf3, 
    0xf3, 
    0xe7, 
    0xcf
};
static const tImage Font_0x29 = { image_data_Font_0x29,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2a[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ████∙█████
    // █∙██∙██∙██
    // ██∙█∙█∙███
    // ███∙∙∙████
    // ██∙█∙█∙███
    // █∙██∙██∙██
    // ████∙█████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf7, 0xc0, 
    0xb6, 0xc0, 
    0xd5, 0xc0, 
    0xe3, 0xc0, 
    0xd5, 0xc0, 
    0xb6, 0xc0, 
    0xf7, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x2a = { image_data_Font_0x2a,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2b[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █████∙██████
    // █████∙██████
    // █████∙██████
    // █████∙██████
    // █∙∙∙∙∙∙∙∙∙██
    // █████∙██████
    // █████∙██████
    // █████∙██████
    // █████∙██████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xfb, 0xf0, 
    0xfb, 0xf0, 
    0xfb, 0xf0, 
    0xfb, 0xf0, 
    0x80, 0x30, 
    0xfb, 0xf0, 
    0xfb, 0xf0, 
    0xfb, 0xf0, 
    0xfb, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x2b = { image_data_Font_0x2b,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2c[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █∙∙∙█
    // █∙∙██
    // █∙∙██
    // ∙∙███
    // ∙∙███
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0x88, 
    0x98, 
    0x98, 
    0x38, 
    0x38, 
    0xf8
};
static const tImage Font_0x2c = { image_data_Font_0x2c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2d[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙∙█
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x82, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x2d = { image_data_Font_0x2d,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2e[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // ██∙∙█
    // ██∙∙█
    // ██∙∙█
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xc8, 
    0xc8, 
    0xc8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x2e = { image_data_Font_0x2e,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2f[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ███████∙∙█
    // ███████∙∙█
    // ██████∙∙██
    // ██████∙∙██
    // █████∙∙███
    // █████∙∙███
    // ████∙∙████
    // ███∙∙█████
    // ███∙∙█████
    // ██∙∙██████
    // ██∙∙██████
    // █∙∙███████
    // █∙∙███████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xfe, 0x40, 
    0xfe, 0x40, 
    0xfc, 0xc0, 
    0xfc, 0xc0, 
    0xf9, 0xc0, 
    0xf9, 0xc0, 
    0xf3, 0xc0, 
    0xe7, 0xc0, 
    0xe7, 0xc0, 
    0xcf, 0xc0, 
    0xcf, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x2f = { image_data_Font_0x2f,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x30[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙███
    // ██∙∙██∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙██
    // ███∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe1, 0xc0, 
    0xcc, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0xc0, 
    0xe1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x30 = { image_data_Font_0x30,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x31[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ████∙∙████
    // ██∙∙∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ██∙∙∙∙∙∙██
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf3, 0xc0, 
    0xc3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xc0, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x31 = { image_data_Font_0x31,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x32[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██∙∙∙∙∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ███████∙∙█
    // ██████∙∙██
    // █████∙∙███
    // ████∙∙████
    // ███∙∙█████
    // ██∙∙██████
    // █∙∙∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xc0, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xfe, 0x40, 
    0xfc, 0xc0, 
    0xf9, 0xc0, 
    0xf3, 0xc0, 
    0xe7, 0xc0, 
    0xcf, 0xc0, 
    0x80, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x32 = { image_data_Font_0x32,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x33[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██∙∙∙∙∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ███████∙∙█
    // ████∙∙∙∙██
    // ██████∙∙██
    // ███████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙██
    // ██∙∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xc0, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xfe, 0x40, 
    0xf0, 0xc0, 
    0xfc, 0xc0, 
    0xfe, 0x40, 
    0x9e, 0x40, 
    0x9c, 0xc0, 
    0xc1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x33 = { image_data_Font_0x33,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x34[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████∙∙██
    // █████∙∙∙██
    // ████∙█∙∙██
    // ███∙██∙∙██
    // ██∙███∙∙██
    // █∙████∙∙██
    // █∙∙∙∙∙∙∙∙∙
    // ██████∙∙██
    // ██████∙∙██
    // ██████∙∙██
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xfc, 0xc0, 
    0xf8, 0xc0, 
    0xf4, 0xc0, 
    0xec, 0xc0, 
    0xdc, 0xc0, 
    0xbc, 0xc0, 
    0x80, 0x00, 
    0xfc, 0xc0, 
    0xfc, 0xc0, 
    0xfc, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x34 = { image_data_Font_0x34,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x35[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██∙∙∙∙∙∙∙█
    // ██∙∙██████
    // ██∙∙██████
    // ██∙∙∙∙∙███
    // ██████∙∙██
    // ███████∙∙█
    // ███████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙██
    // ██∙∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xc0, 0x40, 
    0xcf, 0xc0, 
    0xcf, 0xc0, 
    0xc1, 0xc0, 
    0xfc, 0xc0, 
    0xfe, 0x40, 
    0xfe, 0x40, 
    0x9e, 0x40, 
    0x9c, 0xc0, 
    0xc1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x35 = { image_data_Font_0x35,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x36[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ████∙∙∙∙██
    // ██∙∙∙█████
    // ██∙∙██████
    // █∙∙█∙∙∙███
    // █∙∙∙██∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙██
    // ███∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf0, 0xc0, 
    0xc7, 0xc0, 
    0xcf, 0xc0, 
    0x91, 0xc0, 
    0x8c, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0xc0, 
    0xe1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x36 = { image_data_Font_0x36,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x37[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙∙∙█
    // ███████∙∙█
    // ██████∙∙██
    // ██████∙∙██
    // █████∙∙███
    // █████∙∙███
    // ████∙∙████
    // ████∙∙████
    // ███∙∙█████
    // ███∙∙█████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x80, 0x40, 
    0xfe, 0x40, 
    0xfc, 0xc0, 
    0xfc, 0xc0, 
    0xf9, 0xc0, 
    0xf9, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xe7, 0xc0, 
    0xe7, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x37 = { image_data_Font_0x37,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x38[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██∙∙∙∙∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙∙∙∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙∙∙∙∙██
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xc0, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xc0, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xc0, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x38 = { image_data_Font_0x38,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x39[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙███
    // ██∙∙██∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙∙█
    // ███∙∙∙█∙∙█
    // ██████∙∙██
    // █████∙∙∙██
    // ██∙∙∙∙████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe1, 0xc0, 
    0xcc, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0x40, 
    0xe2, 0x40, 
    0xfc, 0xc0, 
    0xf8, 0xc0, 
    0xc3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x39 = { image_data_Font_0x39,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3a[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██████
    // ██████
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xfc, 
    0xfc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x3a = { image_data_Font_0x3a,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3b[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██████
    // ██████
    // ██∙∙∙█
    // ██∙∙██
    // ██∙∙██
    // █∙∙███
    // █∙∙███
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xfc, 
    0xfc, 
    0xc4, 
    0xcc, 
    0xcc, 
    0x9c, 
    0x9c, 
    0xfc
};
static const tImage Font_0x3b = { image_data_Font_0x3b,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3c[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████∙∙██
    // ██████∙∙████
    // ████∙∙██████
    // ██∙∙████████
    // █∙██████████
    // ██∙∙████████
    // ████∙∙██████
    // ██████∙∙████
    // ████████∙∙██
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0x30, 
    0xfc, 0xf0, 
    0xf3, 0xf0, 
    0xcf, 0xf0, 
    0xbf, 0xf0, 
    0xcf, 0xf0, 
    0xf3, 0xf0, 
    0xfc, 0xf0, 
    0xff, 0x30, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x3c = { image_data_Font_0x3c,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3d[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █∙∙∙∙∙∙∙∙∙██
    // ████████████
    // ████████████
    // ████████████
    // █∙∙∙∙∙∙∙∙∙██
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0x80, 0x30, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0x80, 0x30, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x3d = { image_data_Font_0x3d,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3e[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █∙∙█████████
    // ███∙∙███████
    // █████∙∙█████
    // ███████∙∙███
    // █████████∙██
    // ███████∙∙███
    // █████∙∙█████
    // ███∙∙███████
    // █∙∙█████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0x9f, 0xf0, 
    0xe7, 0xf0, 
    0xf9, 0xf0, 
    0xfe, 0x70, 
    0xff, 0xb0, 
    0xfe, 0x70, 
    0xf9, 0xf0, 
    0xe7, 0xf0, 
    0x9f, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x3e = { image_data_Font_0x3e,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3f[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙∙██
    // █∙∙███∙∙█
    // ██████∙∙█
    // █████∙∙██
    // ████∙∙███
    // ███∙∙████
    // ███∙∙████
    // █████████
    // ███∙∙████
    // ███∙∙████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc1, 0x80, 
    0x9c, 0x80, 
    0xfc, 0x80, 
    0xf9, 0x80, 
    0xf3, 0x80, 
    0xe7, 0x80, 
    0xe7, 0x80, 
    0xff, 0x80, 
    0xe7, 0x80, 
    0xe7, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x3f = { image_data_Font_0x3f,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x40[34] = {
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // █████∙∙∙∙∙████
    // ███∙∙█████∙███
    // ██∙████████∙██
    // ██∙██∙∙∙∙∙██∙█
    // █∙██∙∙██∙∙██∙█
    // █∙██∙∙██∙∙██∙█
    // █∙██∙∙██∙∙██∙█
    // █∙██∙∙██∙∙██∙█
    // ██∙██∙∙∙∙∙∙∙██
    // ██∙███████████
    // ███∙∙█████████
    // █████∙∙∙∙∙████
    // ██████████████
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xf8, 0x3c, 
    0xe7, 0xdc, 
    0xdf, 0xec, 
    0xd8, 0x34, 
    0xb3, 0x34, 
    0xb3, 0x34, 
    0xb3, 0x34, 
    0xb3, 0x34, 
    0xd8, 0x0c, 
    0xdf, 0xfc, 
    0xe7, 0xfc, 
    0xf8, 0x3c, 
    0xff, 0xfc
};
static const tImage Font_0x40 = { image_data_Font_0x40,
    14, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x41[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙████
    // ████∙∙∙████
    // ████∙∙∙████
    // ███∙∙█∙∙███
    // ███∙∙█∙∙███
    // ██∙∙███∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙███∙∙██
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf1, 0xe0, 
    0xf1, 0xe0, 
    0xf1, 0xe0, 
    0xe4, 0xe0, 
    0xe4, 0xe0, 
    0xce, 0x60, 
    0xc0, 0x60, 
    0xce, 0x60, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x41 = { image_data_Font_0x41,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x42[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙∙∙∙∙∙███
    // █∙∙████∙∙██
    // █∙∙████∙∙██
    // █∙∙████∙∙██
    // █∙∙∙∙∙∙∙███
    // █∙∙████∙∙██
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙████∙∙██
    // █∙∙∙∙∙∙∙███
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x80, 0xe0, 
    0x9e, 0x60, 
    0x9e, 0x60, 
    0x9e, 0x60, 
    0x80, 0xe0, 
    0x9e, 0x60, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9e, 0x60, 
    0x80, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x42 = { image_data_Font_0x42,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x43[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙∙∙██
    // ██∙∙████∙∙█
    // ██∙∙████∙∙█
    // █∙∙████████
    // █∙∙████████
    // █∙∙████████
    // █∙∙████████
    // ██∙∙████∙∙█
    // ██∙∙████∙∙█
    // ████∙∙∙∙∙██
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf0, 0x60, 
    0xcf, 0x20, 
    0xcf, 0x20, 
    0x9f, 0xe0, 
    0x9f, 0xe0, 
    0x9f, 0xe0, 
    0x9f, 0xe0, 
    0xcf, 0x20, 
    0xcf, 0x20, 
    0xf0, 0x60, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x43 = { image_data_Font_0x43,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x44[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙∙∙∙∙████
    // █∙∙████∙∙██
    // █∙∙████∙∙██
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙████∙∙██
    // █∙∙████∙∙██
    // █∙∙∙∙∙∙████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x81, 0xe0, 
    0x9e, 0x60, 
    0x9e, 0x60, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9e, 0x60, 
    0x9e, 0x60, 
    0x81, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x44 = { image_data_Font_0x44,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x45[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙∙∙█
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    // █∙∙∙∙∙∙∙∙█
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    // █∙∙∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x80, 0x40, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x80, 0x40, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x80, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x45 = { image_data_Font_0x45,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x46[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙∙∙∙∙∙█
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙∙∙∙∙∙█
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x80, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x80, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x46 = { image_data_Font_0x46,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x47[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙∙∙██
    // ██∙∙████∙∙█
    // ██∙∙████∙∙█
    // █∙∙████████
    // █∙∙████████
    // █∙∙███∙∙∙∙█
    // █∙∙█████∙∙█
    // ██∙∙████∙∙█
    // ██∙∙████∙∙█
    // ████∙∙∙∙∙██
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf0, 0x60, 
    0xcf, 0x20, 
    0xcf, 0x20, 
    0x9f, 0xe0, 
    0x9f, 0xe0, 
    0x9c, 0x20, 
    0x9f, 0x20, 
    0xcf, 0x20, 
    0xcf, 0x20, 
    0xf0, 0x60, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x47 = { image_data_Font_0x47,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x48[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙∙∙∙∙∙∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x80, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x48 = { image_data_Font_0x48,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x49[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // █∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0x81, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x49 = { image_data_Font_0x49,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4a[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // ████∙∙██
    // ∙∙∙∙∙███
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc1, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xf3, 
    0x07, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x4a = { image_data_Font_0x4a,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4b[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙█████∙∙█
    // █∙∙████∙∙██
    // █∙∙███∙∙███
    // █∙∙██∙∙████
    // █∙∙█∙∙█████
    // █∙∙∙∙∙█████
    // █∙∙∙█∙∙████
    // █∙∙███∙∙███
    // █∙∙████∙∙██
    // █∙∙█████∙∙█
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9f, 0x20, 
    0x9e, 0x60, 
    0x9c, 0xe0, 
    0x99, 0xe0, 
    0x93, 0xe0, 
    0x83, 0xe0, 
    0x89, 0xe0, 
    0x9c, 0xe0, 
    0x9e, 0x60, 
    0x9f, 0x20, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x4b = { image_data_Font_0x4b,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4c[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙∙∙∙∙∙∙
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x80, 0x00, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x4c = { image_data_Font_0x4c,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4d[34] = {
    // █████████████
    // █████████████
    // █████████████
    // █████████████
    // █∙∙██████∙∙∙█
    // █∙∙∙█████∙∙∙█
    // █∙∙∙████∙∙∙∙█
    // █∙█∙∙███∙█∙∙█
    // █∙█∙∙██∙∙█∙∙█
    // █∙██∙∙█∙██∙∙█
    // █∙██∙∙∙∙██∙∙█
    // █∙███∙∙███∙∙█
    // █∙███∙∙███∙∙█
    // █∙████████∙∙█
    // █████████████
    // █████████████
    // █████████████
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0x9f, 0x88, 
    0x8f, 0x88, 
    0x8f, 0x08, 
    0xa7, 0x48, 
    0xa6, 0x48, 
    0xb2, 0xc8, 
    0xb0, 0xc8, 
    0xb9, 0xc8, 
    0xb9, 0xc8, 
    0xbf, 0xc8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8
};
static const tImage Font_0x4d = { image_data_Font_0x4d,
    13, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4e[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙██████∙█
    // █∙∙∙█████∙█
    // █∙█∙∙████∙█
    // █∙██∙∙███∙█
    // █∙██∙∙███∙█
    // █∙███∙∙██∙█
    // █∙████∙∙█∙█
    // █∙████∙∙█∙█
    // █∙█████∙∙∙█
    // █∙██████∙∙█
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9f, 0xa0, 
    0x8f, 0xa0, 
    0xa7, 0xa0, 
    0xb3, 0xa0, 
    0xb3, 0xa0, 
    0xb9, 0xa0, 
    0xbc, 0xa0, 
    0xbc, 0xa0, 
    0xbe, 0x20, 
    0xbf, 0x20, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x4e = { image_data_Font_0x4e,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4f[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████∙∙∙∙████
    // ██∙∙████∙∙██
    // ██∙∙████∙∙██
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // ██∙∙████∙∙██
    // ██∙∙████∙∙██
    // ████∙∙∙∙████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xf0, 0xf0, 
    0xcf, 0x30, 
    0xcf, 0x30, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0xcf, 0x30, 
    0xcf, 0x30, 
    0xf0, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x4f = { image_data_Font_0x4f,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x50[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙███
    // █∙∙███∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙██
    // █∙∙∙∙∙∙███
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x81, 0xc0, 
    0x9c, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9c, 0xc0, 
    0x81, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x50 = { image_data_Font_0x50,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x51[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████∙∙∙∙████
    // ██∙∙████∙∙██
    // ██∙∙████∙∙██
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // ██∙∙████∙∙██
    // ██∙∙████∙∙██
    // ████∙∙∙∙∙███
    // ██████∙∙████
    // ██████∙∙████
    // ███████∙∙∙∙█
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xf0, 0xf0, 
    0xcf, 0x30, 
    0xcf, 0x30, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0xcf, 0x30, 
    0xcf, 0x30, 
    0xf0, 0x70, 
    0xfc, 0xf0, 
    0xfc, 0xf0, 
    0xfe, 0x10
};
static const tImage Font_0x51 = { image_data_Font_0x51,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x52[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙∙∙∙∙∙███
    // █∙∙████∙∙██
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙████∙∙██
    // █∙∙∙∙∙∙∙███
    // █∙∙███∙∙███
    // █∙∙████∙∙██
    // █∙∙█████∙∙█
    // █∙∙██████∙∙
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x80, 0xe0, 
    0x9e, 0x60, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9e, 0x60, 
    0x80, 0xe0, 
    0x9c, 0xe0, 
    0x9e, 0x60, 
    0x9f, 0x20, 
    0x9f, 0x80, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x52 = { image_data_Font_0x52,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x53[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙∙██
    // ██∙∙███∙∙█
    // █∙∙████∙∙█
    // █∙∙███████
    // ██∙∙∙∙∙███
    // ███∙∙∙∙∙██
    // ███████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙██
    // ██∙∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe0, 0xc0, 
    0xce, 0x40, 
    0x9e, 0x40, 
    0x9f, 0xc0, 
    0xc1, 0xc0, 
    0xe0, 0xc0, 
    0xfe, 0x40, 
    0x9e, 0x40, 
    0x9c, 0xc0, 
    0xc1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x53 = { image_data_Font_0x53,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x54[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙∙∙█
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x80, 0x40, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x54 = { image_data_Font_0x54,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x55[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // ██∙∙███∙∙██
    // ███∙∙∙∙∙███
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0xce, 0x60, 
    0xe0, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x55 = { image_data_Font_0x55,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x56[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // █∙∙█████∙∙█
    // ██∙∙███∙∙██
    // ██∙∙███∙∙██
    // ██∙∙███∙∙██
    // ███∙∙█∙∙███
    // ███∙∙█∙∙███
    // ████∙∙∙████
    // ████∙∙∙████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0x9f, 0x20, 
    0xce, 0x60, 
    0xce, 0x60, 
    0xce, 0x60, 
    0xe4, 0xe0, 
    0xe4, 0xe0, 
    0xf1, 0xe0, 
    0xf1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x56 = { image_data_Font_0x56,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x57[34] = {
    // ████████████████
    // ████████████████
    // ████████████████
    // ████████████████
    // █∙∙████∙∙████∙∙█
    // █∙∙████∙∙████∙∙█
    // █∙∙███∙∙∙∙███∙∙█
    // ██∙∙██∙██∙██∙∙██
    // ██∙∙█∙∙██∙∙█∙∙██
    // ██∙∙█∙∙██∙∙█∙∙██
    // ██∙∙█∙████∙█∙∙██
    // ███∙∙∙████∙∙∙███
    // ███∙∙██████∙∙███
    // ███∙∙██████∙∙███
    // ████████████████
    // ████████████████
    // ████████████████
    0xff, 0xff, 
    0xff, 0xff, 
    0xff, 0xff, 
    0xff, 0xff, 
    0x9e, 0x79, 
    0x9e, 0x79, 
    0x9c, 0x39, 
    0xcd, 0xb3, 
    0xc9, 0x93, 
    0xc9, 0x93, 
    0xcb, 0xd3, 
    0xe3, 0xc7, 
    0xe7, 0xe7, 
    0xe7, 0xe7, 
    0xff, 0xff, 
    0xff, 0xff, 
    0xff, 0xff
};
static const tImage Font_0x57 = { image_data_Font_0x57,
    16, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x58[34] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙█████∙∙█
    // ██∙∙███∙∙██
    // ██∙∙███∙∙██
    // ███∙∙█∙∙███
    // ████∙∙∙████
    // ████∙∙∙████
    // ███∙∙█∙∙███
    // ██∙∙███∙∙██
    // ██∙∙███∙∙██
    // █∙∙█████∙∙█
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9f, 0x20, 
    0xce, 0x60, 
    0xce, 0x60, 
    0xe4, 0xe0, 
    0xf1, 0xe0, 
    0xf1, 0xe0, 
    0xe4, 0xe0, 
    0xce, 0x60, 
    0xce, 0x60, 
    0x9f, 0x20, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x58 = { image_data_Font_0x58,
    11, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x59[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ∙∙██████∙∙
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙██
    // ███∙∙∙∙███
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x3f, 0x00, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0xc0, 
    0xe1, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x59 = { image_data_Font_0x59,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5a[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙∙∙█
    // ███████∙∙█
    // ██████∙∙██
    // █████∙∙███
    // ████∙∙████
    // ████∙∙████
    // ███∙∙█████
    // ██∙∙██████
    // █∙∙███████
    // █∙∙∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x80, 0x40, 
    0xfe, 0x40, 
    0xfc, 0xc0, 
    0xf9, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xe7, 0xc0, 
    0xcf, 0xc0, 
    0x9f, 0xc0, 
    0x80, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x5a = { image_data_Font_0x5a,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5b[17] = {
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙∙█
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙████
    // ██∙∙∙∙∙█
    0xff, 
    0xff, 
    0xff, 
    0xc1, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xcf, 
    0xc1
};
static const tImage Font_0x5b = { image_data_Font_0x5b,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5c[34] = {
    // ██████████
    // ██████████
    // ██████████
    // █∙∙███████
    // █∙∙███████
    // ██∙∙██████
    // ██∙∙██████
    // ███∙∙█████
    // ███∙∙█████
    // ████∙∙████
    // █████∙∙███
    // █████∙∙███
    // ██████∙∙██
    // ██████∙∙██
    // ███████∙∙█
    // ███████∙∙█
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0xcf, 0xc0, 
    0xcf, 0xc0, 
    0xe7, 0xc0, 
    0xe7, 0xc0, 
    0xf3, 0xc0, 
    0xf9, 0xc0, 
    0xf9, 0xc0, 
    0xfc, 0xc0, 
    0xfc, 0xc0, 
    0xfe, 0x40, 
    0xfe, 0x40, 
    0xff, 0xc0
};
static const tImage Font_0x5c = { image_data_Font_0x5c,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5d[17] = {
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // ████∙∙██
    // █∙∙∙∙∙██
    0xff, 
    0xff, 
    0xff, 
    0x83, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0xf3, 
    0x83
};
static const tImage Font_0x5d = { image_data_Font_0x5d,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5e[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █████∙██████
    // ████∙∙∙█████
    // ███∙∙█∙∙████
    // ██∙∙███∙∙███
    // █∙∙█████∙∙██
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xfb, 0xf0, 
    0xf1, 0xf0, 
    0xe4, 0xf0, 
    0xce, 0x70, 
    0x9f, 0x30, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x5e = { image_data_Font_0x5e,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5f[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ∙∙∙∙∙∙∙∙∙∙
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x00, 0x00, 
    0xff, 0xc0
};
static const tImage Font_0x5f = { image_data_Font_0x5f,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x60[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙█████
    // ████∙∙████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe7, 0xc0, 
    0xf3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x60 = { image_data_Font_0x60,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x61[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙∙██
    // ██████∙∙█
    // ██████∙∙█
    // ██∙∙∙∙∙∙█
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // ██∙∙∙∙∙∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc1, 0x80, 
    0xfc, 0x80, 
    0xfc, 0x80, 
    0xc0, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0xc0, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x61 = { image_data_Font_0x61,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x62[34] = {
    // ██████████
    // ██████████
    // ██████████
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    // █∙∙█∙∙∙███
    // █∙∙∙██∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙██
    // █∙∙∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x91, 0xc0, 
    0x8c, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9c, 0xc0, 
    0x81, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x62 = { image_data_Font_0x62,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x63[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ███∙∙∙∙█
    // ██∙∙██∙∙
    // █∙∙█████
    // █∙∙█████
    // █∙∙█████
    // █∙∙█████
    // ██∙∙██∙∙
    // ███∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xe1, 
    0xcc, 
    0x9f, 
    0x9f, 
    0x9f, 
    0x9f, 
    0xcc, 
    0xe1, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x63 = { image_data_Font_0x63,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x64[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ███████∙∙█
    // ███████∙∙█
    // ███████∙∙█
    // ███∙∙∙∙∙∙█
    // ██∙∙███∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙∙█
    // ███∙∙∙█∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xfe, 0x40, 
    0xfe, 0x40, 
    0xfe, 0x40, 
    0xe0, 0x40, 
    0xce, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0x40, 
    0xe2, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x64 = { image_data_Font_0x64,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x65[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ███∙∙∙∙██
    // ██∙∙██∙∙█
    // █∙∙███∙∙█
    // █∙∙∙∙∙∙∙█
    // █∙∙██████
    // █∙∙██████
    // ██∙∙██∙∙█
    // ███∙∙∙∙██
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xe1, 0x80, 
    0xcc, 0x80, 
    0x9c, 0x80, 
    0x80, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0xcc, 0x80, 
    0xe1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x65 = { image_data_Font_0x65,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x66[17] = {
    // ██████
    // ██████
    // ██████
    // ███∙∙∙
    // ██∙∙██
    // ██∙∙██
    // █∙∙∙∙∙
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██∙∙██
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xe0, 
    0xcc, 
    0xcc, 
    0x80, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xcc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x66 = { image_data_Font_0x66,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x67[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙∙∙█
    // ██∙∙███∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙∙█
    // ███∙∙∙█∙∙█
    // ███████∙∙█
    // ██████∙∙██
    // ██∙∙∙∙∙███
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe0, 0x40, 
    0xce, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0x40, 
    0xe2, 0x40, 
    0xfe, 0x40, 
    0xfc, 0xc0, 
    0xc1, 0xc0
};
static const tImage Font_0x67 = { image_data_Font_0x67,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x68[34] = {
    // ██████████
    // ██████████
    // ██████████
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    // █∙∙█∙∙∙∙██
    // █∙∙∙███∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x90, 0xc0, 
    0x8e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x68 = { image_data_Font_0x68,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x69[17] = {
    // ████
    // ████
    // ████
    // █∙∙█
    // █∙∙█
    // ████
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0x90, 
    0x90, 
    0xf0, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x69 = { image_data_Font_0x69,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6a[17] = {
    // ██████
    // ██████
    // ██████
    // ███∙∙█
    // ███∙∙█
    // ██████
    // ██∙∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ███∙∙█
    // ∙∙∙∙██
    0xfc, 
    0xfc, 
    0xfc, 
    0xe4, 
    0xe4, 
    0xfc, 
    0xc4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0xe4, 
    0x0c
};
static const tImage Font_0x6a = { image_data_Font_0x6a,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6b[34] = {
    // █████████
    // █████████
    // █████████
    // █∙∙██████
    // █∙∙██████
    // █∙∙██████
    // █∙∙███∙∙█
    // █∙∙██∙∙██
    // █∙∙█∙∙███
    // █∙∙∙∙████
    // █∙∙∙∙∙███
    // █∙∙██∙∙██
    // █∙∙███∙∙█
    // █∙∙████∙∙
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9f, 0x80, 
    0x9c, 0x80, 
    0x99, 0x80, 
    0x93, 0x80, 
    0x87, 0x80, 
    0x83, 0x80, 
    0x99, 0x80, 
    0x9c, 0x80, 
    0x9e, 0x00, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x6b = { image_data_Font_0x6b,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6c[17] = {
    // ████
    // ████
    // ████
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // █∙∙█
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0x90, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x6c = { image_data_Font_0x6c,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6d[34] = {
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // █∙∙█∙∙∙██∙∙∙██
    // █∙∙∙██∙∙∙██∙∙█
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // ██████████████
    // ██████████████
    // ██████████████
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0x91, 0x8c, 
    0x8c, 0x64, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc
};
static const tImage Font_0x6d = { image_data_Font_0x6d,
    14, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6e[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙█∙∙∙∙██
    // █∙∙∙███∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x90, 0xc0, 
    0x8e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x6e = { image_data_Font_0x6e,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6f[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙███
    // ██∙∙██∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙██
    // ███∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe1, 0xc0, 
    0xcc, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0xc0, 
    0xe1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x6f = { image_data_Font_0x6f,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x70[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙█∙∙∙███
    // █∙∙∙██∙∙██
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙██
    // █∙∙∙∙∙∙███
    // █∙∙███████
    // █∙∙███████
    // █∙∙███████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x91, 0xc0, 
    0x8c, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9c, 0xc0, 
    0x81, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0, 
    0x9f, 0xc0
};
static const tImage Font_0x70 = { image_data_Font_0x70,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x71[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙∙∙█
    // ██∙∙███∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // ██∙∙██∙∙∙█
    // ███∙∙∙█∙∙█
    // ███████∙∙█
    // ███████∙∙█
    // ███████∙∙█
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe0, 0x40, 
    0xce, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0xcc, 0x40, 
    0xe2, 0x40, 
    0xfe, 0x40, 
    0xfe, 0x40, 
    0xfe, 0x40
};
static const tImage Font_0x71 = { image_data_Font_0x71,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x72[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙█∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙████
    // █∙∙████
    // █∙∙████
    // █∙∙████
    // █∙∙████
    // █∙∙████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x90, 
    0x80, 
    0x9e, 
    0x9e, 
    0x9e, 
    0x9e, 
    0x9e, 
    0x9e, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x72 = { image_data_Font_0x72,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x73[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙██
    // █∙∙███∙█
    // █∙∙█████
    // █∙∙∙∙∙██
    // ██∙∙∙∙∙█
    // █████∙∙█
    // █∙███∙∙█
    // ██∙∙∙∙██
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc3, 
    0x9d, 
    0x9f, 
    0x83, 
    0xc1, 
    0xf9, 
    0xb9, 
    0xc3, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x73 = { image_data_Font_0x73,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x74[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // █∙∙███
    // █∙∙███
    // ∙∙∙∙∙∙
    // █∙∙███
    // █∙∙███
    // █∙∙███
    // █∙∙███
    // █∙∙███
    // █∙∙███
    // ██∙∙∙∙
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0x9c, 
    0x9c, 
    0x00, 
    0x9c, 
    0x9c, 
    0x9c, 
    0x9c, 
    0x9c, 
    0x9c, 
    0xc0, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x74 = { image_data_Font_0x74,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x75[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙███∙∙∙█
    // ██∙∙∙∙█∙∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x9c, 0x40, 
    0xc2, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x75 = { image_data_Font_0x75,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x76[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // ██∙∙█∙∙██
    // ██∙∙█∙∙██
    // ██∙∙█∙∙██
    // ███∙∙∙███
    // ███∙∙∙███
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0xc9, 0x80, 
    0xc9, 0x80, 
    0xc9, 0x80, 
    0xe3, 0x80, 
    0xe3, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x76 = { image_data_Font_0x76,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x77[34] = {
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // ██∙∙██∙∙██∙∙██
    // ██∙∙█∙∙∙∙█∙∙██
    // ██∙∙█∙██∙█∙∙██
    // ███∙∙∙██∙∙∙███
    // ███∙∙∙██∙∙∙███
    // ████∙∙██∙∙████
    // ██████████████
    // ██████████████
    // ██████████████
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0xcc, 0xcc, 
    0xc8, 0x4c, 
    0xcb, 0x4c, 
    0xe3, 0x1c, 
    0xe3, 0x1c, 
    0xf3, 0x3c, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc
};
static const tImage Font_0x77 = { image_data_Font_0x77,
    14, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x78[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // ██∙∙█∙∙██
    // ███∙∙∙███
    // ███∙∙∙███
    // ██∙∙█∙∙██
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0xc9, 0x80, 
    0xe3, 0x80, 
    0xe3, 0x80, 
    0xc9, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x78 = { image_data_Font_0x78,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x79[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // █∙∙███∙∙█
    // ██∙∙█∙∙██
    // ██∙∙█∙∙██
    // ██∙∙█∙∙██
    // ███∙∙∙███
    // ███∙∙∙███
    // ████∙∙███
    // ███∙∙████
    // ███∙∙████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0x9c, 0x80, 
    0xc9, 0x80, 
    0xc9, 0x80, 
    0xc9, 0x80, 
    0xe3, 0x80, 
    0xe3, 0x80, 
    0xf3, 0x80, 
    0xe7, 0x80, 
    0xe7, 0x80
};
static const tImage Font_0x79 = { image_data_Font_0x79,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7a[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // █████∙∙█
    // ████∙∙██
    // ███∙∙███
    // ███∙∙███
    // ██∙∙████
    // █∙∙█████
    // █∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xf9, 
    0xf3, 
    0xe7, 
    0xe7, 
    0xcf, 
    0x9f, 
    0x81, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x7a = { image_data_Font_0x7a,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7b[34] = {
    // ██████████
    // ██████████
    // ██████████
    // █████∙∙∙∙█
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ███∙∙█████
    // █∙∙∙██████
    // ███∙∙█████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // █████∙∙∙∙█
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf8, 0x40, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xe7, 0xc0, 
    0x8f, 0xc0, 
    0xe7, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf8, 0x40
};
static const tImage Font_0x7b = { image_data_Font_0x7b,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7c[17] = {
    // ████████
    // ████████
    // ████████
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    0xff, 
    0xff, 
    0xff, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7
};
static const tImage Font_0x7c = { image_data_Font_0x7c,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7d[34] = {
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙█████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // █████∙∙███
    // ██████∙∙∙█
    // █████∙∙███
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // █∙∙∙∙█████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x87, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf9, 0xc0, 
    0xfc, 0x40, 
    0xf9, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0x87, 0xc0
};
static const tImage Font_0x7d = { image_data_Font_0x7d,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7e[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ███∙∙█████∙█
    // ██∙██∙████∙█
    // █∙███∙∙███∙█
    // █∙████∙██∙██
    // █∙█████∙∙███
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xe7, 0xd0, 
    0xdb, 0xd0, 
    0xb9, 0xd0, 
    0xbd, 0xb0, 
    0xbe, 0x70, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x7e = { image_data_Font_0x7e,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc290[34] = {
    // ███████████████
    // ███████████████
    // ███∙∙███∙∙██∙∙█
    // ███∙∙██∙∙∙∙∙∙∙∙
    // ███∙∙███∙∙██∙∙█
    // █∙∙∙∙∙∙█∙∙∙∙∙∙█
    // █∙∙∙∙∙∙███∙∙███
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙█∙∙█∙∙
    // █∙∙∙∙∙∙∙∙█∙∙█∙∙
    // ███∙∙██∙∙∙∙∙∙∙∙
    // ███∙∙██∙∙∙██∙∙∙
    // ███∙∙∙∙∙∙████∙∙
    // ███∙∙∙∙∙∙████∙∙
    // █∙∙∙█∙∙∙∙███∙∙∙
    // ███████████████
    // ███████████████
    0xff, 0xfe, 
    0xff, 0xfe, 
    0xe7, 0x32, 
    0xe6, 0x00, 
    0xe7, 0x32, 
    0x81, 0x02, 
    0x81, 0xce, 
    0x80, 0x00, 
    0x80, 0x48, 
    0x80, 0x48, 
    0xe6, 0x00, 
    0xe6, 0x30, 
    0xe0, 0x78, 
    0xe0, 0x78, 
    0x88, 0x70, 
    0xff, 0xfe, 
    0xff, 0xfe
};
static const tImage Font_0xc290 = { image_data_Font_0xc290,
    15, 17, 8};
#endif


static const tChar Font_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font_0x21},
#else
  // character: '!' == ''
  {0x21, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font_0x22},
#else
  // character: '"' == ''
  {0x22, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font_0x23},
#else
  // character: '#' == ''
  {0x23, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font_0x24},
#else
  // character: '$' == ''
  {0x24, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font_0x26},
#else
  // character: '&' == ''
  {0x26, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font_0x27},
#else
  // character: ''' == ''
  {0x27, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font_0x28},
#else
  // character: '(' == ''
  {0x28, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font_0x29},
#else
  // character: ')' == ''
  {0x29, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font_0x60},
#else
  // character: '`' == ''
  {0x60, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &Font_0x6c},
#else
  // character: 'l' == ''
  {0x6c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font_0x73},
#else
  // character: 's' == ''
  {0x73, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font_0x74},
#else
  // character: 't' == ''
  {0x74, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Font_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font_0x7e},
#else
  // character: '~' == ''
  {0x7e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0090'
  {0xc290, &Font_0xc290}
#else
  // character: '\x0090' == ''
  {0xc290, &Font_0x}
#endif

};


const tFont Font = { 96, Font_array };

